### PR TITLE
Bump version to 1.0.1

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge-admin, please add noarch: python

**Comment by vamega** [comment]
This looks good, I'll try to merge when the travis build completes. If I forget over this weekend just mention me and I'll get to it.

Thanks for the update.

**Comment by nehaljwani** [comment]
The travis build failed due to an old image? I re-triggered it :(

**Comment by jakirkham** [comment]
Travis CI actually shouldn't be running here. Would report the issue to Travis CI's issue tracker repo and maybe push a new commit to see if it goes away.

**Comment by nehaljwani** [comment]
A re-push solved this. Thanks @jakirkham !

**Comment by jakirkham** [comment]
Sounds like transient bug with Travis CI then. Glad it went away. Though we should still share it with Travis CI so it can get resolved.

**Pull request merged**
